<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/9/19 0019
 * Time: 18:16
 */

namespace app\www\controller;


use think\Controller;
use app\admin\model\LianxiwomenModel;

class ContentusController extends Controller
{
    private $Lianxiwomen;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->Lianxiwomen = new LianxiwomenModel();
    }

    public function lian_xwm(){
        return $this->fetch('lian_xwm');
    }
    //联系我们提交
    public function post_contentus()
    {
        try{
            //初始为300
            $res = ["stat" => "300"];

            $data = input('post.');//通过助手将POST所有数据交给 data

            $validate = validate('Contentus');//实例化 验证器
            if (!$validate->check($data)) {
                $err_id = $validate->getError();
                return show($err_id, $validate->get_message($err_id), [], 200);
            }
            if($this->Lianxiwomen->where('lx_phone',$data['lx_phone'])->find()){
                return show(300,"此手机号已经提交",[],200);
            }
            if($data['lx_language']=='ar') {
                $data['lx_language'] = 'ae';
            }
            $this->Lianxiwomen->data([
                'lx_language' => $data['lx_language'],
                'lx_name' => $data['lx_name'],
                'lx_email' => $data['lx_email'],
                'lx_county_daima' => $data['lx_county_daima'],
                'lx_phone' => $data['lx_phone'],
            ]);
            $this->Lianxiwomen->save();
        }catch (\Exception $e){
            return show(300,"提交失败",[],200);
        }
        return show(200,"提交成功",[],200);
    }
}