<?php
/**
 * Created by PhpStorm.
 * User: administarot
 * Date: 2018/9/10
 * Time: 22:51
 */



namespace app\www\controller;

use think\Controller;
use think\Db;
use think\Request;
use app\admin\model\YeWuModel;

class ibkController extends Controller
{
    private $ye_wu;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->ye_wu = new YeWuModel();
    }

    //公司介绍
    public function company_introduction_cn(){
        return $this->fetch("company_introduction_cn");
    }
    //组织架构
    public function framework_cn(){
        return $this->fetch('framework_cn');
    }
    //重要成员列表
    public function member_list_cn(){
        return $this->fetch('member_list_cn');
    }
    //重要成员info
    public function member_info_cn(){
        return $this->fetch('member_info_cn');
    }
    //主营业务
    public function business_cn(){
        $list = $this->ye_wu->order('order')->paginate(2);
        $imgpath=config("ye_wu_upload_path");
        $this->assign('imgpath',$imgpath);
        $this->assign('list',$list);
        return $this->fetch('business_cn');
    }
}